In [1]:
import pandas as pd
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [2]:
ds = pd.read_csv("../results/merge_res_teaser.csv")

In [5]:
ds.head()

,commit,created,deleted,poisoned,message,message_status
0,swh:1:rev:99ec619f2cfe0639ca846178b2d6b6eb3f9ea07d,NaN,tkcode,False,Merge pull request #1 from testerSunshine/master\n\nupdate,Utf8
1,swh:1:rev:6fa4020593497555321bac9e89b963edbdbcf830,NaN,"damatuCode/__init__.py,.idea/workspace.xml,.idea/inspectionProfiles/Project_Default.xml,damatuCode/ruokuai.py",False,Merge pull request #271 from taochenlove/master\n\nfix warning:YAMLLoadWarning: calling yaml.load() without Loader=... i…,Utf8
2,swh:1:rev:b2416455f471752fb1b91bb9468769b5f724784d,NaN,tkcode,False,Merge pull request #103 from pyfaith/master\n\n修正查询余票时，不显示当前cdn轮询IP问题,Utf8
3,swh:1:rev:37f20eda21b68dea8509107e1d69b66bf855564d,NaN,tkcode,False,Merge pull request #101 from cclauss/patch-4\n\nUse feature detection instead of version detection,Utf8
4,swh:1:rev:34789a5a3ebfe87ed650d6997b8a97914fd28f8c,NaN,tkcode,False,Merge pull request #99 from cclauss/patch-2\n\nDefine raw_input() in Python 3,Utf8

In [ ]:
# More robust parsing with error handling
try:
    ds = pd.read_csv("../results/merge_res_full.csv", 
                     on_bad_lines='skip',
                     engine='python',
                     quoting=3,
                     escapechar='\\')
except:
    # If all else fails, read line by line and skip problematic rows
    import csv
    rows = []
    with open("../results/merge_res_full.csv", 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader)
        for i, row in enumerate(reader):
            try:
                if len(row) == len(header):  # Ensure row has correct number of columns
                    rows.append(row)
            except:
                print(f"Skipping problematic row {i+2}")
                continue
    
    ds = pd.DataFrame(rows, columns=header)

In [13]:
import pickle
with open("../results/merge_res_full.pkl", 'wb') as f:
    pickle.dump(ds, f)

In [14]:
import time
start = time.time()
with open("../results/merge_res_full.pkl", 'rb') as f:
    ds2 = pickle.load(f)
print(f"elapsed: {time.time() - start}")

elapsed: 0.5019557476043701

In [3]:
len(ds)

146465

In [4]:
ds.head()

,commit,created,deleted,poisoned,message,message_status
0,swh:1:rev:734b555b01ad0674ccd10144f327fc6164e7d488,NaN,".idea/markdown-navigator/profiles_settings.xml,.idea/vcs.xml,.idea/12306.iml,.idea/markdown-exported-files.xml,.idea/modules.xml,.idea/workspace.xml,.idea/misc.xml,.idea/inspectionProfiles/Project_Default.xml,.idea/markdown-navigator.xml",False,Merge pull request #187 from ferried/master\n\nremove settings of Interlij Idea,Utf8
1,swh:1:rev:37f20eda21b68dea8509107e1d69b66bf855564d,NaN,tkcode,False,Merge pull request #101 from cclauss/patch-4\n\nUse feature detection instead of version detection,Utf8
2,swh:1:rev:34789a5a3ebfe87ed650d6997b8a97914fd28f8c,NaN,tkcode,False,Merge pull request #99 from cclauss/patch-2\n\nDefine raw_input() in Python 3,Utf8
3,swh:1:rev:805cdfcbdf2bf65ab8deb31e9033d5a8f4dd440b,NaN,config/ticket_config.yaml,False,Merge remote-tracking branch 'remotes/origin/master' into py3.6-support\n\n# Conflicts:\n#\tconfig/AutoSynchroTime.py\n#\tinit/select_ticket_info.py\n#\tinter/GetPassengerDTOs.py\n,Utf8
4,swh:1:rev:b5de9386ad562cb441875fab1641484d592fad86,NaN,docker.sh,False,Merge branch 'master' of https://github.com/testerSunshine/12306\n,Utf8

In [6]:
ds['poisoned'].value_counts()

poisoned
False    123228
True      23253
Name: count, dtype: int64

In [7]:
ds_not_poisoned = ds[ds['poisoned']==False][['commit', 'created', 'deleted']]

In [8]:
ds_not_poisoned_created_only = ds_not_poisoned[ds_not_poisoned['deleted'].isna()][['commit', 'created']]
print(f'created only cases: {len(ds_not_poisoned_created_only):,}')

created only cases: 521

In [9]:
ds_not_poisoned_created_only

                                                    commit  \
53      swh:1:rev:3eeb73ef120d535e8388b567b663e95438b4cc8e
86      swh:1:rev:404791bbe2c149d48d65c92d24ec53963cc18192
937     swh:1:rev:03582a3dbd1b4643b7b70cf277eada66dcb0800e
1085    swh:1:rev:be84c8d1e4fb8426d23b288838e58826cf086b55
1464    swh:1:rev:f01d1358f80588e3e766af574cf7d8327018b863
...                                                    ...
126041  swh:1:rev:b3270a89cfe6f5f9e854c5a1a5d9cd2a9b4d6d54
126710  swh:1:rev:a57d6a6848bb4745f6b6a727389bc684ec2690f4
126749  swh:1:rev:94eb28aeb5abf9afd73e7079e8e1922fa549b87f
126914  swh:1:rev:b71b12484aafdaa533250248d50abfcaaf12912c
127172  swh:1:rev:1c32c1a35aa32ea304b38c9b32a848af1d07d943

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           created
53      dash/html/_imports_.py,dash/html/__init__.py,dash/html/package-info.json,dash/html/dash_html_components.min.js,dash/html/metadata.json,dash/html/ObjectEl.py,dash/html/Iframe.py,dash/html/dash_html_components.min.js.map,dash/html/Video.py,dash/html/Link.py,dash/html/Form.py,dash/html/Img.py,dash/html/Li.py,dash/html/Embed.py,dash/html/P.py,dash/html/Br.py,dash/html/Content.py,dash/html/Details.py,dash/html/Area.py,dash/html/Frame.py,dash/html/Thead.py,dash/html/Big.py,dash/html/Sup.py,dash/html/Xmp.py,dash/html/Dfn.py,dash/html/U.py,dash/html/Footer.py,dash/html/Tfoot.py,dash/html/Address.py,dash/html/Samp.py,dash/html/Ruby.py,dash/html/Tr.py,dash/html/Noscript.py,dash/html/H2.py,dash/html/H1.py,dash/html/Code.py,dash/html/Ins.py,dash/html/Canvas.py,dash/html/Progress.py,dash/html/Rp.py,dash/html/Plaintext.py,dash/html/Q.py,dash/html/Picture.py,dash/html/Article.py,dash/html/Output.py,dash/html/Rtc.py,dash/html/Mark.py,dash/html/Option.py,dash/html/Basefont.py,dash/html/Aside.py,dash/html/Nav.py,dash/html/Button.py,dash/html/H4.py,dash/html/I.py,dash/html/Bdi.py,dash/html/Kbd.py,dash/html/Data.py,dash/html/Track.py,dash/html/H5.py,dash/html/Var.py,dash/html/Table.py,dash/html/Nobr.py,dash/html/Rb.py,dash/html/Legend.py,dash/html/Label.py,dash/html/Strike.py,dash/html/Summary.py,dash/html/Main.py,dash/html/Figure.py,dash/html/Optgroup.py,dash/html/Section.py,dash/html/Base.py,dash/html/Meta.py,dash/html/Source.py,dash/html/Header.py,dash/html/Figcaption.py,dash/html/H6.py,dash/html/Datalist.py,dash/html/Td.py,dash/html/Col.py,dash/html/Rt.py,dash/html/Em.py,dash/html/Dt.py,dash/html/Del.py,dash/html/Pre.py,dash/html/Fieldset.py,dash/html/Hgroup.py,dash/html/Tbody.py,dash/html/Cite.py,dash/html/Select.py,dash/html/Bdo.py,dash/html/Template.py,dash/html/Audio.py,dash/html/Abbr.py,dash/html/Dd.py,dash/html/Div.py,dash/html/Center.py,dash/html/Shadow.py,dash/html/Sub.py,dash/html/H3.py,dash/html/Blink.py,dash/html/Dl.py,dash/html/Hr.py,dash/html/A.py,dash/html/Small.py,dash/html/Font.py,dash/html/Keygen.py,dash/html/Ol.py,dash/html/S.py,dash/html/Blockquote.py,dash/html/Marquee.py,dash/html/Spacer.py,dash/html/Acronym.py,dash/html/Frameset.py,dash/html/Caption.py,dash/html/MapEl.py,dash/html/B.py,dash/html/Wbr.py,dash/html/Time.py,dash/html/Span.py,dash/html/Script.py,dash/html/Th.py,dash/html/Meter.py,dash/html/Ul.py,dash/html/Textarea.py,dash/html/Colgroup.py,dash/html/Slot.py,dash/html/Strong.py,dash/html/Dialog.py,dash/html/Param.py,dash/html/Title.py,dash/dash_table/FormatTemplate.py,dash/dash_table/_imports_.py,dash/dash_table/Format.py,dash/dash_table/__init__.py,dash/dash_table/async-table.js,dash/dash_table/index.html,dash/dash_table/async-highlight.js,dash/dash_table/async-table.js.LICENSE.txt,dash/dash_table/metadata.json,dash/dash_table/async-table.js.map,dash/dash_table/async-export.js,dash/dash_table/DataTable.py,dash/dash_table/async-highlight.js.map,dash/dash_table/async-export.js.map,dash/dash_table/package-info.json,dash/dash_table/demo.js.map,dash/dash_table/bundle.js,dash/dash_table/demo.js,dash/dash_table/bundle.js.map,dash/dash_table/.gitkeep,dash/dcc/express.py,dash/dcc/async-dropdown.js.LICENSE.txt,dash/dcc/async-plotlyjs.js.LICENSE.txt,dash/dcc/async-markdown.js.LICENSE.txt,dash/dcc/_imports_.py,dash/dcc/Tooltip.py,dash/dcc/async-graph.js.map,dash/dcc/async-graph.js,dash/dcc/plotly.min.js,dash/dcc/dash_core_components.js,dash/dcc/async-plotlyjs.js,dash/dcc/metadata.json,dash/dcc/dash_core_components.js.map,dash/dcc/__init__.py,dash/dcc/async-highlight.js.map,dash/dcc/async-highlight.js,dash/dcc/async-markdown.js,dash/dcc/async-slider.js.map,dash/dcc/async-dropdown.js,dash/dcc/dash_core_components-shared.js.LICENSE.txt,dash/dcc/Upload.py,dash/dcc/Store.py,dash/dcc/LogoutButton.py,dash/dcc/Graph.py,dash/dcc/async-upload.js,dash/dcc/Loading.py,dash/dcc/Dropdown.py,dash/dcc/Clipboard.py,dash/dcc/async-slider.js,dash/dcc/Input.py,dash/dcc/RadioItems.py,dash/dcc/async-datepicker.js.map,dash/dcc/Tab.py,dash/dcc/ConfirmDialog.py,dash/dcc/dash_core_components-shared.js.map,dash/dcc/Interval.py,dash/dcc/async-dropdown.js.map,dash/dcc/RangeSlider.py,dash/dcc/dash_core_components-shared.js,dash/dcc/async-datepicker.js,dash/dcc/async-upload.js.map,dash/dcc/DatePickerRange.py,dash/dcc/Download.py,dash/dcc/Location.py,dash/dcc/Markdown.py,dash/dcc/Tabs.py,dash/dcc/Textarea.py,dash/dcc/DatePickerSingle.py,dash/dcc/Link.py,dash/dcc/async-markdown.js.map,dash/dcc/Checklist.py,dash/dcc/ConfirmDialogProvider.py,dash/dcc/Slider.py,dash/dcc/dash_core_components.js.LICENSE.txt,dash/dcc/package-info.json,dash/dcc/.gitkeep
86                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              dash-renderer/lib/AccessDenied.react.js,dash-renderer/lib/AppContainer.react.js,dash-renderer/lib/DashRenderer.js,dash-renderer/lib/TreeContainer.js,dash-renderer/lib/AppProvider.react.js,dash-renderer/lib/APIController.react.js,dash-renderer/lib/store.js,dash-renderer/lib/persistence.js,dash-renderer/lib/checkPropTypes.js,dash-renderer/lib/registry.js,dash-renderer/lib/index.js,dash-renderer/lib/exceptions.js,dash-renderer/lib/isSimpleComponent.js,dash-renderer/lib/components/core/Loading.react.js,dash-renderer/lib/components/core/DocumentTitle.react.js,dash-renderer/lib/components/core/Reloader.react.js,dash-renderer/lib/components/core/Toolbar.react.js,dash-renderer/lib/components/error/GlobalErrorOverlay.css,dash-renderer/lib/components/error/Percy.css,dash-renderer/lib/components/error/werkzeugcss.js,dash-renderer/lib/components/error/GlobalErrorOverlay.react.js,dash-renderer/lib/components/error/ComponentErrorBoundary.react.js,dash-renderer/lib/components/error/GlobalErrorContainer.react.js,dash-renderer/lib/components/error/GlobalErrorContainerPassthrough.react.js,dash-renderer/lib/components/error/CallbackGraph/CallbackGraphContainer.react.js,dash-renderer/lib/components/error/CallbackGraph/CallbackGraphContainer.css,dash-renderer/lib/components/error/menu/DebugMenu.css,dash-renderer/lib/components/error/menu/DebugAlertContainer.css,dash-renderer/lib/components/error/menu/DebugAlertContainer.react.js,dash-renderer/lib/components/error/menu/DebugMenu.react.js,dash-renderer/lib/components/error/FrontEnd/FrontEndError.css,dash-renderer/lib/components/error/FrontEnd/FrontEndErrorContainer.react.js,dash-renderer/lib/components/error/FrontEnd/FrontEndError.react.js,dash-renderer/lib/actions/index.js,dash-renderer/lib/actions/dependencies.js,dash-renderer/lib/actions/api.js,dash-renderer/lib/actions/constants.js,dash-renderer/lib/actions/paths.js,dash-renderer/lib/actions/utils.js,dash-renderer/lib/actions/isAppReady.js,dash-renderer/lib/reducers/dependencyGraph.js,dash-renderer/lib/reducers/layout.js,dash-renderer/lib/reducers/constants.js,dash-renderer/lib/reducers/api.js,dash-renderer/lib/reducers/config.js,dash-renderer/lib/reducers/paths.js,dash-renderer/lib/reducers/appLifecycle.js,dash-renderer/lib/reducers/history.js,dash-renderer/lib/reducers/hooks.js,dash-renderer/lib/reducers/pendingCallbacks.js,dash-renderer/lib/reducers/reducer.js,dash-renderer/lib/reducers/error.js,dash-renderer/lib/styles/styles.js,dash-renderer/lib/constants/constants.js
937                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             doc/Makefile,doc/summarize.py,doc/postprocess.py,doc/README.txt,doc/source/bugs.rst,doc/source/scipyshiny_small.png,doc/source/glossary.rst,doc/source/about.rst,doc/source/conf.py,doc/source/contents.rst,doc/source/license.rst,doc/source/user/basics.broadcasting.rst,doc/source/user/basics.rst,doc/source/user/c-info.rst,doc/source/user/misc.rst,doc/source/user/howtofind.rst,doc/source/user/basics.rec.rst,doc/source/user/performance.rst,doc/source/user/basics.creation.rst,doc/source/user/basics.subclassing.rst,doc/source/user/basics.types.rst,doc/source/user/index.rst,doc/source/user/basics.indexing.rst,doc/source/user/c-info.beyond-basics.rst,doc/source/user/c-info.how-to-extend.rst,doc/source/user/c-info.python-as-glue.rst,doc/source/_static/scipy.css,doc/source/_templates/indexsidebar.html,doc/source/_templates/indexcontent.html,doc/source/_templates/layout.html,doc/source/reference/routines.ctypeslib.rst,doc/source/reference/routines.financial.rst,doc/source/reference/routines.err.rst,doc/source/reference/routines.window.rst,doc/source/reference/routines.bitwise.rst,doc/source/reference/routines.functional.rst,doc/source/reference/arrays.interface.rst,doc/source/reference/arrays.rst,doc/source/reference/ufuncs.rst,doc/source/reference/c-api.rst,doc/source/reference/routines.set.rst,doc/source/reference/index.rst,doc/source/reference/routines.indexing.rst,doc/source/reference/c-api.types-and-structures.rst,doc/source/reference/routines.fft.rst,doc/source/reference/routines.array-creation.rst,doc/source/reference/c-api.array.rst,doc/source/reference/c-api.dtype.rst,doc/source/reference/routines.math.rst,doc/source/reference/c-api.ufunc.rst,doc/source/reference/routines.rst,doc/source/reference/arrays.indexing.rst,doc/source/reference/internals.code-explanations.rst,doc/source/reference/routines.statistics.rst,doc/source/reference/routines.array-manipulation.rst,doc/source/reference/distutils.rst,doc/source/reference/arrays.dtypes.rst,doc/source/reference/arrays.scalars.rst,doc/source/reference/routines.io.rst,doc/source/reference/routines.ma.rst,doc/source/reference/c-api.config.rst,doc/source/reference/routines.emath.rst,doc/source/reference/arrays.ndarray.rst,doc/source/reference/arrays.classes.rst,doc/source/reference/routines.numarray.rst,doc/source/reference/routines.matlib.rst,doc/source/reference/routines.oldnumeric.rst,doc/source/reference/routines.poly.rst,doc/source/reference/routines.sort.rst,doc/source/reference/routines.dtype.rst,doc/source/reference/routines.linalg.rst,doc/source/reference/routines.help.rst,doc/source/reference/internals.rst,doc/source/reference/routines.other.rst,doc/source/reference/routines.dual.rst,doc/source/reference/routines.logic.rst,doc/source/reference/routines.random.rst,doc/source/reference/figures/dtype-hierarchy.dia,doc/source/reference/figures/threefundamental.fig,doc/source/reference/figures/dtype-hierarchy.pdf,doc/source/reference/figures/threefundamental.png,doc/source/reference/figures/threefundamental.pdf,doc/source/reference/figures/dtype-hierarchy.png

In [ ]:
all_filenames = []
for created_files in ds_not_poisoned_created_only['created']:
    if pd.notna(created_files):
        file_paths = [path.strip() for path in created_files.split(',')]
        filenames = [os.path.basename(path) for path in file_paths if path.strip()]
        all_filenames.extend(filenames)

In [21]:
filename_counts = pd.Series(all_filenames).value_counts()
print(f'Total unique filenames: {len(filename_counts):,}')
print(f'Total filename occurrences: {len(all_filenames):,}')

Total unique filenames: 3,462
Total filename occurrences: 4,540

In [23]:
filename_counts.head(10)

__init__.py          188
spec.png              50
original.wav          50
finetuned.wav         50
no_finetuning.wav     50
intro.rst             20
datasets.rst          20
README.md             20
configs.rst           20
checkpoint.rst        16
Name: count, dtype: int64

In [35]:
filename_counts[filename_counts.index.str.contains('__init__.py', na=False)]

__init__.py                    188
__init__.py.orig                 8
__init__.py~upstream_master      2
__init__.py~HEAD                 2
__init__.pyi                     1
Name: count, dtype: int64