In [1]:
import pandas as pd
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [2]:
ds = pd.read_csv("../results/merge_res_teaser_v3.csv")

In [3]:
len(ds)

146472

In [4]:
ds.head()

,commit,created,deleted,poisoned,message,message_status
0,swh:1:rev:b5de9386ad562cb441875fab1641484d592fad86,NaN,docker.sh,False,Merge branch 'master' of https://github.com/testerSunshine/12306\n,Utf8
1,swh:1:rev:99ec619f2cfe0639ca846178b2d6b6eb3f9ea07d,NaN,tkcode,False,Merge pull request #1 from testerSunshine/master\n\nupdate,Utf8
2,swh:1:rev:15491c8aa63f6a49f5a0954dd390bd7da0630974,NaN,tkcode,False,Merge pull request #100 from cclauss/patch-3\n\nDefine xrange() in Python 3,Utf8
3,swh:1:rev:b2416455f471752fb1b91bb9468769b5f724784d,NaN,tkcode,False,Merge pull request #103 from pyfaith/master\n\n修正查询余票时，不显示当前cdn轮询IP问题,Utf8
4,swh:1:rev:0d561034eb5c8b52495b75823a7c590c3133bfd3,NaN,tkcode,False,update docker-compose\n,Utf8

In [4]:
ds['poisoned'].value_counts()

KeyError: 'poisoned'

In [17]:
ds_not_poisoned = ds[ds['poisoned']==False][['commit', 'created', 'deleted']]

In [18]:
ds_not_poisoned_created_only = ds_not_poisoned[ds_not_poisoned['deleted'].isna()][['commit', 'created']]
print(f'created only cases: {len(ds_not_poisoned_created_only):,}')

created only cases: 0

In [19]:
ds_not_poisoned_created_only

Empty DataFrame
Columns: [commit, created]
Index: []

In [ ]:
all_filenames = []
for created_files in ds_not_poisoned_created_only['created']:
    if pd.notna(created_files):
        file_paths = [path.strip() for path in created_files.split(',')]
        filenames = [os.path.basename(path) for path in file_paths if path.strip()]
        all_filenames.extend(filenames)

In [21]:
filename_counts = pd.Series(all_filenames).value_counts()
print(f'Total unique filenames: {len(filename_counts):,}')
print(f'Total filename occurrences: {len(all_filenames):,}')

Total unique filenames: 3,462
Total filename occurrences: 4,540

In [23]:
filename_counts.head(10)

__init__.py          188
spec.png              50
original.wav          50
finetuned.wav         50
no_finetuning.wav     50
intro.rst             20
datasets.rst          20
README.md             20
configs.rst           20
checkpoint.rst        16
Name: count, dtype: int64

In [35]:
filename_counts[filename_counts.index.str.contains('__init__.py', na=False)]

__init__.py                    188
__init__.py.orig                 8
__init__.py~upstream_master      2
__init__.py~HEAD                 2
__init__.pyi                     1
Name: count, dtype: int64