In [1]:
import pandas as pd
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_colwidth', None)

In [2]:
df = pd.read_csv("../data_privacy_v2.csv")

In [3]:
df

,swhid,keyword,message
0,swh:1:rev:46696bd9b0118dc49d4f225d668a7e8cbdd3...,GDPR,HDDS-2014. Create Symmetric Key for GDPR (#136...
1,swh:1:rev:d061c8469f6ada5e0068752e0621307a804b...,GDPR,HDDS-2140. Add robot test for GDPR feature\n\n...
2,swh:1:rev:c55ac6a1c7d1dc65a0d2e735b315bbf6898f...,GDPR,HDDS-2174. Delete GDPR Encryption Key from met...
3,swh:1:rev:5c963a75d648cb36e7e36884f61616831229...,GDPR,HDDS-2016. Add option to enforce GDPR in Bucke...
4,swh:1:rev:685918ef41a9fff51a1a84718097b90b4a91...,GDPR,HDDS-2227. GDPR key generation could benefit f...
5,swh:1:rev:23274b56bea0f502a5c74877a5631fb0e12a...,GDPR,Add integration for Osano/GDPR (#17565)\n\n
6,swh:1:rev:6856f991ca8cd6ff829adf3b1fccb5162dd1...,GDPR,Add integration for Osano/GDPR (#17565)\n\n
7,swh:1:rev:9d7244dc3702e9943362493b716043bb9785...,GDPR,Add integration for Osano/GDPR (#17565)\n\n
8,swh:1:rev:abfe001f0abedcc5750c2da072b6d04fcc5b...,GDPR,Add integration for Osano/GDPR\n
9,swh:1:rev:c7f6b420aeba24e9a216d7a013a1f313637c...,GDPR,Merge pull request #3448 from matrix-org/matth...
10,swh:1:rev:1e788db430344c897b185de831b385a81c23...,GDPR,add GDPR erase param to deactivate API\n
11,swh:1:rev:fd99787162113857119c033355548c5b3769...,GDPR,Incorporate Dave's work for GDPR login flows\n...
12,swh:1:rev:b29a3f747df710480237146fdb0f41284298...,GDPR,Explain better what GDPR-erased means\n\nFixes...
13,swh:1:rev:cca03dbec8abde03aeb9348a4d9a12b2808f...,GDPR,Merge tag 'v1.20.0rc1' into develop\n\nSynapse...
14,swh:1:rev:b5133dd97f693ca213b30f4f3e874e9ab395...,GDPR,Explain better what GDPR-erased means (#8189)\...
15,swh:1:rev:2bd022e04c6c1a82a73376db8999db0b29ed...,GDPR,Merge commit 'abeab964d' into anoa/dinsic_rele...
16,swh:1:rev:871198137b66c73c468a88291f3f882a0a1a...,GDPR,Merge branch 'develop' of github.com:matrix-or...
17,swh:1:rev:efdbcfd6aff93e81c7a3cde6ff8cfe027f6c...,GDPR,Merge tag 'v1.56.0rc1' into develop\n\nSynapse...
18,swh:1:rev:fc2cbb2a63fdcf6aed36ac8711b122681aa3...,GDPR,Merge tag 'v1.56.0' into beeper-master\n\nSyna...
19,swh:1:rev:c4210b53714f9c488ed2dbdf2b2715870192...,GDPR,[webtoons] update agegate/GDPR cookies\n
20,swh:1:rev:b779715204dbd544582b7811f0265caca60c...,PIPL,Add PIPL API (#1214)\n\n
21,swh:1:rev:34c268e4a4784e62bce32224372549a6f1b1...,PIPL,"Remove PIPL, it's broken\n"
22,swh:1:rev:f78ba34f924be6ec41ef244fc5b00cf4b2d2...,GDPR,Add GTM to docs (#22509)\n\n## Summary & Motiv...
23,swh:1:rev:7c03cf55bb552da902281ae76483a97ff948...,PECR,Include Scientific Python's Plausible analytic...
24,swh:1:rev:a178a5b4158b5009bcd29fc7399dd21c2d9c...,GDPR,fix(jira): Users not showing up in JIRA server...
25,swh:1:rev:99ed5da6168cee746435eb520e5b59bd0205...,GDPR,fix(jira) Use the query parameter instead of u...
26,swh:1:rev:07f9b3b5cef2ad444a78f5d0823ee3cbe3ee...,GDPR,fix(jira) Use the query parameter instead of u...
27,swh:1:rev:9c21c04bb15b769dcaac197a6aa681d9b139...,GDPR,Merge branch 'master' into feature/project-opt...
28,swh:1:rev:643056e6132698be12c3cc420b1cbdb22990...,GDPR,feat(jira) Update Jira integration to comply w...
29,swh:1:rev:4cb7aa8cc882eeb12fcfb7c78ec171d1290e...,GDPR,feat(replays): Implement metadata-less storage...
30,swh:1:rev:64f426172346c7125e99c72904b47a126ad9...,GDPR,fix: Change user foreign keys to use `models.S...
31,swh:1:rev:2a2c4907cdc897651c153662822d7292fbf4...,GDPR,fix: Change user foreign keys to use `models.S...
32,swh:1:rev:9a30831f82260065330f14ca3df06139700e...,GDPR,fix(jira) Remove broken jira glance\n\nThe Jir...
33,swh:1:rev:f655f74521494b44a588edb8e58a82e069ba...,GDPR,feat(jira) Update Jira integration to comply w...
34,swh:1:rev:78562962995b05bed11ecde93a1af8888b90...,GDPR,fix(jira) Remove broken jira glance (#23119)\n...
35,swh:1:rev:15738907c762e6e4b0fae1baba91d04e0bb2...,GDPR,GDPR fix for Google?\n\nThe only problem for E...
36,swh:1:rev:0adde0f2ec470f6f8f9dfafdc3fc927ca35c...,GDPR,Merge pull request #393 from kingpitka/master\...

In [13]:
df["keyword"].value_counts()

keyword
GDPR    34
PIPL     2
PECR     1
Name: count, dtype: int64

In [15]:
df[df["keyword"]=="PECR"]

,swhid,keyword,message
23,swh:1:rev:7c03cf55bb552da902281ae76483a97ff948d7f7,PECR,"Include Scientific Python's Plausible analytics\n\nScientific Python offered us to use their plausible instance for our\nwebsite analytics. Plausible [1] self-describes as ""No cookies and fully\ncompliant with GDPR, CCPA and PECR"" and should hopefully gain us some\ninsights into our users in a privacy-friendly manner.\n\nDocumentation for the inclusion in our theme can be found here:\nhttps://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/analytics.html\n\n[1] https://plausible.io\n"